name: macOS VNC

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-15-intel
    timeout-minutes: 360

    steps:
      - name: Informacoes
        run: |
          sw_vers
          uname -m
          echo "Usuario: $USER"

      - name: Criar senha do usuario
        run: |
          sudo dscl . -passwd /Users/runner "Mac123456!"

      - name: Instalar Tailscale
        run: |
          brew install tailscale
          sudo brew services start tailscale
          sleep 5

      - name: Login Tailscale
        run: |
          sudo tailscale up

      - name: Tentar ativar Screen Sharing
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure \
            -allowAccessFor -allUsers \
            -privs -all \
            -restart -agent -menu || true

          sudo lsof -iTCP:5900 -sTCP:LISTEN || true

      - name: Mostrar IP
        run: |
          sudo tailscale ip -4

      - name: Manter Mac ligado
        run: |
          sleep 21000
